name: Atualizar Painel Macro

on:
  schedule:
    - cron: '0 9 * * 1-5' # Roda automaticamente de segunda a sexta às 09:00 UTC (06:00 BRT)
  workflow_dispatch: # Permite rodar manualmente se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install pandas requests

    - name: Executar Script de Coleta
      run: python coletor.py

    - name: Dar Push no HTML atualizado
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add index.html
        git commit -m "Atualização automática dos dados: $(date +'%d/%m/%Y')" || exit 0
        git push
